import {test,expect} from '@playwright/test';
import {labs} from '../../site/src/atlas/catalog.mjs';
const range=async(page,label,value)=>page.getByRole('slider',{name:label,exact:true}).evaluate((input,n)=>{input.value=String(n);input.dispatchEvent(new Event('input',{bubbles:true}));},value);

test('visual atlas has ninety distinct labs, filtering and interactive home layers',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:'02 Layout',exact:true}).click();await expect(page.locator('.hero-system')).toHaveAttribute('data-layer','layout');
 await page.goto('./#/atlas');await expect(page.locator('.atlas-card')).toHaveCount(90);await page.getByRole('button',{name:'Performance',exact:true}).click();await expect(page.locator('.atlas-card')).toHaveCount(labs.filter(l=>l.category==='Performance').length);await page.getByRole('button',{name:'All labs',exact:true}).click();await page.getByRole('textbox',{name:'Search visual labs'}).fill('Async race');await expect(page.locator('.atlas-card')).toHaveCount(1);
});
for(const lab of labs)test(`visual atlas scene renders without errors: ${lab.id}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./#/atlas/'+lab.id);await expect(page.locator('.visual-lab')).toHaveAttribute('data-lab',lab.id);await expect(page.locator('#visual-metrics output')).toHaveCount(3);await expect(page.locator('#visual-code')).not.toBeEmpty();await expect(page.locator('.visual-scope')).toContainText(lab.scope);expect(await page.locator('.v-scene > svg').innerHTML()).not.toMatch(/NaN|undefined/);const initialStep=Number(await page.locator('.visual-lab').getAttribute('data-step'));await page.getByRole('button',{name:'Next step',exact:true}).click();await expect(page.locator('#stage-title')).toHaveText(lab.steps[initialStep+1][0]);expect(errors).toEqual([]);
});
test('visual atlas layout conserves width, handles constrained overflow and direct dragging',async({page})=>{
 await page.goto('./#/atlas/layout');await expect(page.locator('#visual-metrics')).toContainText('492');await range(page,'Container width',360);await range(page,'Pixel track',240);await expect(page.locator('.v-scene')).toContainText('Overflow: 68 u');await expect(page.locator('#visual-metrics output').nth(2)).toHaveText('0 u');await page.getByRole('button',{name:'Reset experiment',exact:true}).click();
 const handle=page.locator('[data-drag="width"]');const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+70,box.y+box.height/2,{steps:8});await page.mouse.up();expect(+await page.getByRole('slider',{name:'Container width',exact:true}).inputValue()).toBeGreaterThan(800);
 await page.screenshot({path:'artifacts/evidence/visual-layout.png',fullPage:true});
});
test('visual atlas binding distinguishes missing notifications, rebind and TwoWay write-back',async({page})=>{
 await page.goto('./#/atlas/binding');await page.getByLabel('Raise PropertyChanged').uncheck();await page.getByLabel('Source · Title').fill('Changed silently');await expect(page.getByLabel('Target · Text')).toHaveValue('Hello, Uno');await page.getByLabel('Raise PropertyChanged').check();await expect(page.getByLabel('Target · Text')).toHaveValue('Hello, Uno');await page.getByRole('button',{name:'Rebind · read source again'}).click();await expect(page.getByLabel('Target · Text')).toHaveValue('Changed silently');await page.getByLabel('Binding mode').selectOption('TwoWay');await page.getByLabel('Target · Text').fill('Two-way edit');await expect(page.getByLabel('Source · Title')).toHaveValue('Two-way edit');await expect(page.locator('#visual-trace')).toContainText('Write back');await page.screenshot({path:'artifacts/evidence/visual-binding.png',fullPage:true});
});
test('visual atlas reproduces stale async results and exposes the latest-request fix',async({page})=>{
 await page.goto('./#/atlas/race');await page.getByRole('button',{name:'Reproduce race'}).click();await expect(page.locator('#visual-metrics output').last()).toHaveText('Stale');await page.getByRole('button',{name:'Repair policy'}).click();await expect(page.locator('#visual-metrics output').last()).toHaveText('Current');await expect(page.locator('.v-scene')).toContainText('Search “Uno” · accepted');await page.screenshot({path:'artifacts/evidence/visual-race.png',fullPage:true});
});
test('visual atlas state machine enables only legal transitions',async({page})=>{
 await page.goto('./#/atlas/state');await expect(page.getByRole('button',{name:'Complete',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Start load',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('#visual-metrics output').first()).toHaveText('cancelled');await expect(page.getByRole('button',{name:'Retry',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Start load',exact:true}).click();await page.getByRole('button',{name:'Fail',exact:true}).click();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('#visual-metrics output').first()).toHaveText('loading');
});
test('visual atlas local values, virtualization bounds and shared state are inspectable',async({page})=>{
 await page.goto('./#/atlas/precedence');await expect(page.locator('#visual-metrics output').first()).toHaveText('40 pt');await page.getByRole('button',{name:'ClearValue',exact:true}).click();await expect(page.locator('#visual-metrics output').first()).toHaveText('24 pt');
 await page.goto('./#/atlas/virtualization');await range(page,'Data items',10000);expect(+(await page.locator('#visual-metrics output').nth(1).textContent()).trim()).toBeLessThan(20);await page.getByRole('button',{name:'No overscan',exact:true}).click();expect(+(await page.locator('#visual-metrics output').nth(1).textContent()).trim()).toBeLessThanOrEqual(7);
 await page.goto('./#/atlas/layout?'+new URLSearchParams({s:JSON.stringify({width:600,weight:3,unknown:'<script>bad()</script>'})}));await expect(page.getByRole('slider',{name:'Container width',exact:true})).toHaveValue('600');await expect(page.getByRole('slider',{name:'First star weight',exact:true})).toHaveValue('3');
});
test('visual atlas is usable on a narrow screen and respects reduced motion',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('./#/atlas/easing');await expect(page.getByRole('button',{name:'Play explanatory sequence',exact:true})).toBeDisabled();await expect(page.getByRole('slider',{name:'Elapsed progress',exact:true})).toHaveValue('35');await page.getByRole('button',{name:'Next step',exact:true}).click();await expect(page.locator('#stage-title')).toHaveText('Interpolate');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.goto('./#/atlas/layout');await range(page,'Container width',420);await page.screenshot({path:'artifacts/evidence/visual-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('visual atlas preserves keyboard tree focus and dark theme',async({page})=>{
 await page.goto('./#/atlas/tree');const node=page.locator('[data-node="Border"]');await node.focus();await page.keyboard.press('Enter');await expect(node).toBeFocused();await expect(page.getByLabel('Selected object')).toHaveValue('Border');await page.getByRole('button',{name:'Switch color theme'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'artifacts/evidence/visual-dark.png',fullPage:true});
});
