import test from 'node:test';
import assert from 'node:assert/strict';
import {tracks,lessons} from '../site/src/course.mjs';
import {evaluateRules,validateImport,freshProgress,scheduleReview,loadProgress,persistProgress} from '../site/src/progress.mjs';
import {escapeHtml,markdown} from '../site/src/helpers.mjs';
test('fifteen paths, ninety unique guided lessons',()=>{assert.equal(tracks.length,15);assert.equal(lessons.length,90);assert.equal(new Set(lessons.map(l=>l.id)).size,90);for(const t of tracks)assert.equal(t.lessons.length,6);});
for(const l of lessons)test('lesson contract: '+l.id,()=>{assert(l.concepts.length>=3);assert(l.concepts.every(c=>c[1].length>150));assert(l.code.length>100);assert(l.solution!==l.code);assert(l.source);assert(l.quiz.answer>=0&&l.quiz.answer<l.quiz.options.length);assert(evaluateRules(l.solution,l.rules).every(r=>r.passed));assert(l.hints.length>=2);});
test('progress import validates IDs and bounds',()=>{const data=validateImport({version:1,lessons:{events:{completed:true,reviewed:100},bad:{completed:true}},drafts:{events:'x',bad:'x'},notes:{events:'note'},bookmarks:['events','bad','events']},['events']);assert.deepEqual(data.bookmarks,['events']);assert.equal(data.lessons.events.reviewed,20);assert(!data.lessons.bad);assert(!data.drafts.bad);assert.throws(()=>validateImport({version:99},[]));});
test('review schedule advances and resets deterministically',()=>{assert.equal(scheduleReview({},true,0).due,86400000);assert.equal(scheduleReview({reviewed:1},true,0).due,3*86400000);assert.equal(scheduleReview({reviewed:5},false,0).reviewed,0);});
test('storage failure preserves the in-memory state',()=>{const bad={getItem(){throw new Error('denied');},setItem(){throw new Error('full');}};assert.deepEqual(loadProgress(bad),freshProgress());assert.equal(persistProgress(freshProgress(),bad),false);});
test('reference rendering escapes executable markup',()=>{assert.equal(escapeHtml('<script>'),'&lt;script&gt;');const text=markdown('<script>alert(1)</script>\n\n# Safe','https://github.com/unoplatform/uno/');assert(!text.includes('<script>'));assert(text.includes('&lt;script&gt;'));});
