import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {dataWorkspaces} from '../site/src/learning/data-workspaces/lessons.mjs';
import {definitions,convertValue,pageWindow,contentOutcome,versionedCommit,notificationLedger,initialHistory,historyTransition} from '../site/src/learning/data-workspaces/models.mjs';
import {drawScene} from '../site/src/learning/data-workspaces/scenes.mjs';
test('six fully developed source-linked workshops retain independent executable variants',()=>{
 assert.equal(dataWorkspaces.length,6);assert.equal(new Set(dataWorkspaces.map(l=>l.id)).size,6);
 for(const l of dataWorkspaces){assert.equal(l.steps.length,4);assert(l.steps.every(s=>s.explanation.split(/\s+/).length>=65));assert(l.steps.every(s=>s.worked&&s.prompt&&s.answer));assert(l.solution!==l.code);assert(l.solution.includes(l.rules[0].contains));assert(l.references.every(url=>url.startsWith('https://learn.microsoft.com/')));assert(l.code.includes('public static UIElement Build()'));assert(l.objectives.length>=3);}
});
test('converters preserve source, bound precision and return an explicit invalid result',()=>{const r=convertValue({value:.375,digits:1});assert.equal(r.value,.375);assert.equal(r.scaled,37.5);assert.equal(r.rounded,37.5);assert.equal(convertValue({valid:false}).valid,false);assert.equal(convertValue({digits:Infinity}).digits,0);});
test('paging never accepts a duplicate key or exceeds the source boundary',()=>{for(let total=0;total<80;total+=3)for(let loaded=0;loaded<=100;loaded+=7)for(const repeat of [0,1,5,10]){const r=pageWindow({total,loaded,repeat,size:5});assert(r.accepted.every(id=>id>r.loaded&&id<=r.total));assert.equal(new Set(r.accepted).size,r.accepted.length);assert(r.nextLoaded<=r.total);assert.equal(r.duplicates+r.accepted.length,r.received.length);}});
test('empty success, failed refresh and cancellation remain distinguishable',()=>{assert.equal(contentOutcome({phase:'failure',previous:3}).rows,3);assert.equal(contentOutcome({phase:'failure',previous:3}).stale,true);assert.equal(contentOutcome({phase:'empty',previous:3}).rows,0);assert.equal(contentOutcome({phase:'cancelled'}).canRetry,false);assert.equal(contentOutcome({phase:'refreshing'}).canCancel,true);});
test('stale commits cannot change the accepted version; validation precedes commit',()=>{assert.equal(versionedCommit({base:1,current:2}).outcome,'conflict');assert.equal(versionedCommit({base:1,current:2}).nextVersion,2);const r=versionedCommit({base:2,current:2,draft:'  Updated  '});assert.equal(r.outcome,'accepted');assert.equal(r.nextVersion,3);assert.equal(r.acceptedTitle,'Updated');assert.equal(versionedCommit({draft:' '}).outcome,'validation');});
test('collection ledger distinguishes reset from incremental events without claiming timings',()=>{assert.equal(notificationLedger({count:25,strategy:'incremental'}).eventCount,26);assert.equal(notificationLedger({count:25,strategy:'reset'}).eventCount,1);assert.equal(notificationLedger().performance,'Not measured');assert.equal(notificationLedger({count:2,selected:4}).selectionResolvable,false);});
test('linear history invalidates only a new branch, preserves no-op redo and bounds memory',()=>{let s=initialHistory(3);for(const v of ['A','B','C'])s=historyTransition(s,'commit',v);s=historyTransition(s,'undo');assert.equal(s.current,'B');const identical=historyTransition(s,'commit','B');assert.equal(identical,s);assert.equal(identical.future[0],'C');s=historyTransition(s,'commit','D');assert.equal(s.future.length,0);s=historyTransition(s,'undo');assert.equal(s.current,'B');s=historyTransition(s,'redo');assert.equal(s.current,'D');for(let i=0;i<100;i++)s=historyTransition(s,'commit',String(i));assert.equal(s.past.length,3);for(let i=0;i<20;i++)s=historyTransition(s,'undo');assert.equal(s.past.length,0);assert.equal(s.future.length,3);});
test('all workshop diagrams have different non-caption geometry and escaped source values',()=>{const seen=new Set();for(const [id,d] of Object.entries(definitions)){const r=drawScene(id,d.defaults);assert.equal(r.metrics.length,3);assert(!/NaN|undefined|Infinity/.test(r.svg));const g=r.svg.replace(/<text[\s\S]*?<\/text>/g,'');const h=createHash('sha256').update(g).digest('hex');assert(!seen.has(h),id);seen.add(h);}const hostile=drawScene('versioned-commit',{draft:'<script>alert(1)</script>'});assert(!hostile.svg.includes('<script>'));});

import {controlledComparison} from '../site/src/learning/data-workspaces/comparisons.mjs';
test('each inline comparison changes calculated results rather than only a caption',()=>{for(const id of Object.keys(definitions)){const c=controlledComparison(id);assert.notDeepEqual(definitions[id].calculate(c.baseline),definitions[id].calculate(c.changed),id);assert(c.caption.length>45);}});
